"""updated payment  model

Revision ID: 040784a65b40
Revises: 558b77e6adbe
Create Date: 2025-01-28 13:07:58.814327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040784a65b40'
down_revision = '558b77e6adbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sub_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('memo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('network_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('payment_methods_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('image')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('payment_methods_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('network_address')
        batch_op.drop_column('memo')
        batch_op.drop_column('wallet_address')
        batch_op.drop_column('sub_type')
        batch_op.drop_column('account_name')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('method_type')

    # ### end Alembic commands ###
