"""updated payment  model

Revision ID: 50641a4800b2
Revises: 040784a65b40
Create Date: 2025-01-28 15:02:50.481019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50641a4800b2'
down_revision = '040784a65b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
